/**
 * create-prd.test.js
 * Tests for the createPRD functionality
 */

import { jest } from '@jest/globals';

jest.unstable_mockModule('fs', () => {
	const mockFs = {
		existsSync: jest.fn(() => false),
		mkdirSync: jest.fn(),
		writeFileSync: jest.fn(),
		readFileSync: jest.fn()
	};
	return { default: mockFs, ...mockFs };
});

jest.unstable_mockModule('../../../scripts/modules/ai-services-unified.js', () => ({
	generateTextService: jest.fn()
}));

jest.unstable_mockModule('../../../scripts/modules/utils.js', () => ({
	log: jest.fn()
}));

jest.unstable_mockModule('../../../scripts/modules/config-manager.js', () => ({
	getConfig: jest.fn(() => ({}))
}));

const { createPRD } = await import('../../../scripts/modules/task-manager/create-prd.js');
const fs = await import('fs');
const { generateTextService } = await import('../../../scripts/modules/ai-services-unified.js');

import { beforeEach, afterEach, describe, test, expect } from '@jest/globals';
import path from 'path';

describe('createPRD', () => {
	let tempDir;
	let outputPath;

	beforeEach(() => {
		tempDir = '/tmp/test-create-prd';
		outputPath = path.join(tempDir, 'prd.txt');
		
		// Reset mocks
		jest.clearAllMocks();
		
		// Setup default mock returns
		fs.existsSync.mockReturnValue(false);
		generateTextService.mockResolvedValue({
			text: 'Generated PRD content'
		});
	});

	afterEach(() => {
		jest.resetAllMocks();
	});

	test('should create a PRD with basic functionality', async () => {
		const description = 'A task management web application';
		const options = {
			projectRoot: tempDir,
			template: 'standard',
			research: false,
			force: false
		};

		const result = await createPRD(description, outputPath, options);

		expect(result.success).toBe(true);
		expect(result.path).toBe(outputPath);
		expect(fs.mkdirSync).toHaveBeenCalledWith(path.dirname(outputPath), { recursive: true });
		expect(fs.writeFileSync).toHaveBeenCalledWith(outputPath, expect.stringContaining('Generated PRD content'), 'utf8');
		expect(generateTextService).toHaveBeenCalledWith(
			expect.stringContaining(description),
			expect.objectContaining({
				provider: 'main',
				projectRoot: tempDir,
				temperature: 0.3
			})
		);
	});

	test('should use research provider when research option is true', async () => {
		const description = 'A mobile fitness tracking app';
		const options = {
			projectRoot: tempDir,
			template: 'detailed',
			research: true,
			force: false
		};

		await createPRD(description, outputPath, options);

		expect(generateTextService).toHaveBeenCalledWith(
			expect.stringContaining(description),
			expect.objectContaining({
				provider: 'research',
				projectRoot: tempDir,
				temperature: 0.3
			})
		);
	});

	test('should throw error if file exists and force is false', async () => {
		fs.existsSync.mockReturnValue(true); // File exists

		const description = 'Test project';
		const options = {
			projectRoot: tempDir,
			template: 'minimal',
			research: false,
			force: false
		};

		await expect(createPRD(description, outputPath, options)).rejects.toThrow(
			'PRD file already exists at'
		);
	});

	test('should overwrite file when force is true', async () => {
		fs.existsSync.mockReturnValue(true); // File exists

		const description = 'Test project with force';
		const options = {
			projectRoot: tempDir,
			template: 'minimal',
			research: false,
			force: true
		};

		const result = await createPRD(description, outputPath, options);

		expect(result.success).toBe(true);
		expect(fs.writeFileSync).toHaveBeenCalled();
	});

	test('should include template content in AI prompt', async () => {
		const description = 'E-commerce platform';
		const options = {
			projectRoot: tempDir,
			template: 'standard',
			research: false,
			force: false
		};

		await createPRD(description, outputPath, options);

		// Check that the AI service was called with a prompt containing template structure
		const callArgs = generateTextService.mock.calls[0];
		const prompt = callArgs[0];
		
		expect(prompt).toContain(description);
		expect(prompt).toContain('Core Features');
		expect(prompt).toContain('Technical Architecture');
		expect(prompt).toContain('Development Roadmap');
	});

	test('should format PRD response with metadata header', async () => {
		generateTextService.mockResolvedValue({
			text: '# My Project PRD\n\nProject content here'
		});

		const description = 'Test project for formatting';
		const options = {
			projectRoot: tempDir,
			template: 'minimal',
			research: false,
			force: false
		};

		await createPRD(description, outputPath, options);

		const writeCall = fs.writeFileSync.mock.calls[0];
		const writtenContent = writeCall[1];
		
		expect(writtenContent).toContain('Generated by Task Master AI');
		expect(writtenContent).toContain(description.substring(0, 100));
		expect(writtenContent).toContain('# My Project PRD');
	});

	test('should handle AI service errors gracefully', async () => {
		generateTextService.mockRejectedValue(new Error('AI service unavailable'));

		const description = 'Test project';
		const options = {
			projectRoot: tempDir,
			template: 'standard',
			research: false,
			force: false
		};

		await expect(createPRD(description, outputPath, options)).rejects.toThrow(
			'AI service unavailable'
		);
	});
});